version: '3.8'

services:
  web:
    build: .
    container_name: simplesolution_web
    network_mode: bridge 
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=simplesolution.com.br,www.simplesolution.com.br
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=simplesolution.com.br,www.simplesolution.com.br
      - LETSENCRYPT_EMAIL=contato@davimachado.cloud
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`simplesolution.com.br`)"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    restart: always